/// A TypeScript export collected through `inventory`.
pub struct TypescriptExport {
    /// Type name.
    pub name: &'static str,
    /// Emit a TypeScript declaration.
    pub export: fn() -> String,
}

/// Write every collected TypeScript declaration to `path`.
pub fn export_typescript(path: impl AsRef<std::path::Path>) -> crate::Result<()> {
    let mut names = Vec::new();
    let mut body = String::from("// Generated by streamdeck-plugin. Do not edit.\n\n");
    for item in inventory::iter::<TypescriptExport> {
        names.push(item.name);
        body.push_str(&(item.export)());
        if !body.ends_with('\n') {
            body.push('\n');
        }
        body.push('\n');
    }
    if let Some(parent) = path.as_ref().parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, body)?;
    tracing::debug!(?names, "wrote TypeScript contracts");
    Ok(())
}

/// Register a `ts-rs` type for later export.
#[macro_export]
macro_rules! export_ts {
    ($ty:ty) => {
        $crate::inventory::submit! {
            $crate::TypescriptExport {
                name: stringify!($ty),
                export: || <$ty as $crate::TS>::decl(),
            }
        }
    };
}
